// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Course struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Attendants  int64     `json:"attendants"`
	StartDate   time.Time `json:"start_date"`
	EndDate     time.Time `json:"end_date"`
}

type Enrollment struct {
	ID          int64     `json:"id"`
	StudentID   int64     `json:"student_id"`
	CourseID    int64     `json:"course_id"`
	CreatedDate time.Time `json:"created_date"`
}

type School struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Address     string    `json:"address"`
	Type        string    `json:"type"`
	CreatedDate time.Time `json:"created_date"`
}

type Student struct {
	ID          int64     `json:"id"`
	SchoolID    int64     `json:"school_id"`
	Name        string    `json:"name"`
	Password    string    `json:"password"`
	CreatedDate time.Time `json:"created_date"`
}
